language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby
gemfile:
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.6.0.x
  - gemfiles/Gemfile-rails.edge
before_install:
  - gem install bundler -v '< 2'
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
script: bundle exec rake
matrix:
  allow_failures:
    - rvm: jruby
    - gemfile: gemfiles/Gemfile-rails.edge
  fast_finish: true
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-rails.edge
    - rvm: 2.3
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.3
      gemfile: gemfiles/Gemfile-rails.edge
    - rvm: 2.4
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.4
      gemfile: gemfiles/Gemfile-rails.edge
cache: bundler
